### ISSUE TITLE
Selecting a deformable node shows all nodes in scene (Refactor Deformer Array Type)

### ISSUE THREAD

**Issue by nan0m** [cloudofoz/godot-deformablemesh#4]
Not precisely an issue but maybe a QoL improvement. Currently the export variable for deformers is typed as a `Array[NodePath]` this showing all nodes in the scene tree. 
If this were Array[Deformer] or similar, it would only show the relevant nodes in the selection popup.

**Comment by cloudofoz** [comment]
This makes me think that you might be using an older version of my plugin.

The exported variable is already typed as `Array[Deformer]` (`var dm_deformers: Array[Deformer]`). 
You can check the relevant line [here](https://github.com/cloudofoz/godot-deformablemesh/blob/f381d791f453370ed572be55db3cb1d24e25147b/addons/deformablemesh/dm_deformable_mesh.gd#L59).

Let me know if this was the case.

**Comment by nan0m** [comment]
Hi. It's the @export var a few lines up.  It's about this one [here](https://github.com/cloudofoz/godot-deformablemesh/blob/f381d791f453370ed572be55db3cb1d24e25147b/addons/deformablemesh/dm_deformable_mesh.gd#L48)

**Comment by cloudofoz** [comment]
Thank you for highlighting the correct line.

Now that you mention it, I recall there was a specific reason I chose to use NodePath during my tests, though I can't quite remember why at the moment.

That said, this add-on was originally created for an earlier version of Godot, so re-testing it sounds like a good idea!

**Comment by cloudofoz** [comment]
In the first iteration of my add-on, I was "forced" to use `NodePath` for a specific reason during testing, though I can’t recall the exact details.

Thanks to @nan0m's suggestion and feedback, I’ve had the chance to re-evaluate this decision. After reviewing the current state of the add-on, it now makes sense to modify the `@onready @export var deformers: Array[NodePath]` to `@onready @export var deformers: Array[Deformer]`.

I’ve refactored the related functions, and from my tests, everything seems to work fine with the new type.

That said, there is a **known issue** that the **deformers array will be cleared the first time after updating**, so **you'll need to manually re-set the deformers for existing projects**.

I’m looking for feedback on whether this is a significant issue for users or if further adjustments are needed.

I've created [a branch with this modification](https://github.com/cloudofoz/godot-deformablemesh/tree/improve-deformers-selection).

It would be great if anyone could test the changes and confirm that nothing breaks. Your feedback would be much appreciated!
